# Generated by Django 4.0.4 on 2022-06-15 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phonenumber', models.CharField(blank=True, max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
