# Generated by Django 4.0.5 on 2022-06-30 08:49

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_profile_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=authentication.models.user_directory_path, verbose_name='pictures'),
        ),
    ]
