# Generated by Django 4.0.5 on 2022-06-25 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostFeed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
