# Generated by Django 4.0.5 on 2022-06-17 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Feed', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
    ]
